// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvSmG1V7WVF-zkNcIBTB2QKfF1PyXsnOA',
    appId: '1:1060557259571:web:7501549471316ccb4c7446',
    messagingSenderId: '1060557259571',
    projectId: 'authtutorial-9cafa',
    authDomain: 'authtutorial-9cafa.firebaseapp.com',
    storageBucket: 'authtutorial-9cafa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC9fUrPyooCZXWYKFBGBvQEGZVmAlrp-RA',
    appId: '1:1060557259571:android:28c6f8d2aaddeaf64c7446',
    messagingSenderId: '1060557259571',
    projectId: 'authtutorial-9cafa',
    storageBucket: 'authtutorial-9cafa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAa_-C2RlA9PDGLZFbyK38ZGYPgncJhY2I',
    appId: '1:1060557259571:ios:da736ac8772bb3c44c7446',
    messagingSenderId: '1060557259571',
    projectId: 'authtutorial-9cafa',
    storageBucket: 'authtutorial-9cafa.appspot.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAa_-C2RlA9PDGLZFbyK38ZGYPgncJhY2I',
    appId: '1:1060557259571:ios:da736ac8772bb3c44c7446',
    messagingSenderId: '1060557259571',
    projectId: 'authtutorial-9cafa',
    storageBucket: 'authtutorial-9cafa.appspot.com',
    iosBundleId: 'com.example.flutterLoginPage',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAvSmG1V7WVF-zkNcIBTB2QKfF1PyXsnOA',
    appId: '1:1060557259571:web:b45f2f30d0d009bf4c7446',
    messagingSenderId: '1060557259571',
    projectId: 'authtutorial-9cafa',
    authDomain: 'authtutorial-9cafa.firebaseapp.com',
    storageBucket: 'authtutorial-9cafa.appspot.com',
  );
}
